### ISSUE TITLE
Any tip for the server side please?

### ISSUE THREAD

**Issue by wazowski78** [dbof10/ig-direct#1]
Hi, nice job! But could you share some tips for the server side please?

**Comment by dbof10** [comment]
hi, I didn't get any notification.  the server acts as a proxy to interact with private instagram api library

**Comment by wazowski78** [comment]
Thank you dbof10, I mean, how can I install the server side? Some instructions to run the whole project will be very appreciated.

**Comment by dbof10** [comment]
I added in the readme.md. you can check now
